[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja",
    "cmake>=3.12",
    "pybind11[global]>=2.10.4",
    "numpy",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build-verbosity = "3"
build = "cp311-*"
#before-build = "rm -rf {project}/build"
skip = ["*-manylinux_i686", "*-musllinux*"]

[tool.cibuildwheel.linux]
archs = ["x86_64", "aarch64"]

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.cibuildwheel.windows]
archs = ["AMD64", "ARM64"]
